spring.application.name=ebank-bot
spring.ai.openai.api-key=${key-api}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=false
server.port=8059
spring.ai.mcp.client.streamable-http.connections.customer.url=http://localhost:8058/mcp
spring.ai.mcp.client.streamable-http.connections.account.url=http://localhost:8057/mcp
telegram.tocken=${telegram-tocken}
eureka.client.jersey.enabled=false